name: The Republic Returns
favicon: null
layout_spectrum: 0.8188755444716662
typography_spectrum: 0.09261531359516084
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.41029067267663777
  lightness: 0.04157519550062716
  saturation: 0.6305706854909658
  rhythmicContrast: 0.4072925681248307
purpose: []
